print ("hello world")
print ("what is your name")
print ("who are you")
print ("where are you from")
print ("are you male or female")
print ("what country of origine are you")
print ("what nationality are you")
print ("are you a humanbeing")
print ("how many children do you have")
print ("what is you favourite food")
print ("who do you like")
print ("what is your favourite colour")
print ("what is your teacher's name")
print ("how old are you")
print ("do you enjoy going out")
print ("which countries have you visited")
print ("which school did you go to")
print ("what can i do")
